# deployment-test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbo-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wbo-app
  template:
    metadata:
      labels:
        app: wbo-app
    spec:
      containers:
      - name: wbo-app
        image: lovasoa/wbo
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"