# service-prod.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: wbo-app
  ports:
  - port: 80
    targetPort: 5001
    nodePort: 30002